// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAX37swk-j2nVenyV2x5DJA9A_ZCzF_TMU",
    authDomain: "limitly-f5acc.firebaseapp.com",
    projectId: "limitly-f5acc",
    storageBucket: "limitly-f5acc.appspot.com",
    messagingSenderId: "296728430407",
    appId: "1:296728430407:web:8dbf5a2fe108d39800ee62",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNn5uyQ-yn4GeCG5BIn-vfTEdGV-56b18',
    appId: '1:966193389957:android:e25f45e80bc7b7125fa4ec',
    messagingSenderId: '966193389957',
    projectId: 'limitly-f5acc-b2ffc',
    storageBucket: 'limitly-f5acc-b2ffc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoLlWhnRknN8uslj9tHquvjhIGmpLRgko',
    appId: '1:966193389957:ios:1a5ba81c69b62e3e5fa4ec',
    messagingSenderId: '966193389957',
    projectId: 'limitly-f5acc-b2ffc',
    storageBucket: 'limitly-f5acc-b2ffc.firebasestorage.app',
    iosBundleId: 'com.example.limitlyDevelopment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoLlWhnRknN8uslj9tHquvjhIGmpLRgko',
    appId: '1:966193389957:ios:1a5ba81c69b62e3e5fa4ec',
    messagingSenderId: '966193389957',
    projectId: 'limitly-f5acc-b2ffc',
    storageBucket: 'limitly-f5acc-b2ffc.firebasestorage.app',
    iosBundleId: 'com.example.limitlyDevelopment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCquSlUTDv4mW12CaO_1YlEeIw1OFkTbL0',
    appId: '1:966193389957:web:445ba8b5ba7482a25fa4ec',
    messagingSenderId: '966193389957',
    projectId: 'limitly-f5acc-b2ffc',
    authDomain: 'limitly-f5acc-b2ffc.firebaseapp.com',
    storageBucket: 'limitly-f5acc-b2ffc.firebasestorage.app',
    measurementId: 'G-37CD1SENLG',
  );
}
